# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[battery]
display = [
    { style = "red bold", threshold = 10 },
    { style = "yellow bold", threshold = 20 },
]

[shell]
disabled = false
